// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package actionLogService

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/ServiceWeaver/onlineboutique/actionLogService/ActionLogService",
		Iface: reflect.TypeOf((*ActionLogService)(nil)).Elem(),
		Impl:  reflect.TypeOf(impl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return actionLogService_local_stub{impl: impl.(ActionLogService), tracer: tracer, convertAndSendMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/actionLogService/ActionLogService", Method: "ConvertAndSend", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return actionLogService_client_stub{stub: stub, convertAndSendMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/ServiceWeaver/onlineboutique/actionLogService/ActionLogService", Method: "ConvertAndSend", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return actionLogService_server_stub{impl: impl.(ActionLogService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return actionLogService_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[ActionLogService] = (*impl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*impl)(nil)

// Local stub implementations.

type actionLogService_local_stub struct {
	impl                  ActionLogService
	tracer                trace.Tracer
	convertAndSendMetrics *codegen.MethodMetrics
}

// Check that actionLogService_local_stub implements the ActionLogService interface.
var _ ActionLogService = (*actionLogService_local_stub)(nil)

func (s actionLogService_local_stub) ConvertAndSend(ctx context.Context) (err error) {
	// Update metrics.
	begin := s.convertAndSendMetrics.Begin()
	defer func() { s.convertAndSendMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "actionLogService.ActionLogService.ConvertAndSend", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ConvertAndSend(ctx)
}

// Client stub implementations.

type actionLogService_client_stub struct {
	stub                  codegen.Stub
	convertAndSendMetrics *codegen.MethodMetrics
}

// Check that actionLogService_client_stub implements the ActionLogService interface.
var _ ActionLogService = (*actionLogService_client_stub)(nil)

func (s actionLogService_client_stub) ConvertAndSend(ctx context.Context) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.convertAndSendMetrics.Begin()
	defer func() { s.convertAndSendMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "actionLogService.ActionLogService.ConvertAndSend", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.23.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type actionLogService_server_stub struct {
	impl    ActionLogService
	addLoad func(key uint64, load float64)
}

// Check that actionLogService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*actionLogService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s actionLogService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "ConvertAndSend":
		return s.convertAndSend
	default:
		return nil
	}
}

func (s actionLogService_server_stub) convertAndSend(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.ConvertAndSend(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type actionLogService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that actionLogService_reflect_stub implements the ActionLogService interface.
var _ ActionLogService = (*actionLogService_reflect_stub)(nil)

func (s actionLogService_reflect_stub) ConvertAndSend(ctx context.Context) (err error) {
	err = s.caller("ConvertAndSend", ctx, []any{}, []any{})
	return
}
